import pygame
import math

pygame.init()

clock = pygame.time.Clock()

width, height = 600, 400

screen = pygame.display.set_mode((width, height))

frames = 60

class Segment(pygame.sprite.Sprite):
    def __init__(self, x, y, long, angle):
        pygame.sprite.Sprite.__init__(self)
        self.x = x
        self.y = y
        self.long = long
        self.angle = angle
        self.a = pygame.math.Vector2(x, y)
        self.b = pygame.math.Vector2(0, 0)


    def show(self, display):
        pygame.draw.line(display, ((24, 129, 129)), (self.a.x, self.a.y), (self.b.x, self.b.y), 5) 
        

    def calculate_B(self):
        dx = self.long * math.cos(self.angle)
        dy = self.long * math.sin(self.angle)

        self.b = pygame.math.Vector2(self.a.x + dx, self.a.y + dy)

    def update(self):
        self.calculate_B()

    def follow(self, tx, ty):
        
        target = pygame.math.Vector2(tx, ty)
        self.angle = math.atan2(ty - self.a.y, tx - self.a.x)
        self.b.rotate(self.angle)
        self.b = pygame.math.Vector2(tx, ty)
        self.a = -pygame.math.Vector2(self.long * math.cos(self.angle) - tx, self.long * math.sin(self.angle) - ty)
        
        
        
mouse_pos = pygame.mouse.get_pos()

segment1 = Segment(300, 200, 5, 0)
segment2 = Segment(segment1.a.x, segment1.a.y, 5, 0)
segment3 = Segment(segment2.a.x, segment2.a.y, 5, 0)
segment4 = Segment(segment3.a.x, segment3.a.y, 5, 0)
segment5 = Segment(segment4.a.x, segment4.a.y, 5, 0)
segment6 = Segment(segment5.a.x, segment5.a.y, 5, 0)
segment7 = Segment(segment6.a.x, segment6.a.y, 5, 0)
segment8 = Segment(segment7.a.x, segment7.a.y, 5, 0)
segment9 = Segment(segment8.a.x, segment8.a.y, 5, 0)
segment10 = Segment(segment9.a.x, segment9.a.y, 5, 0)
segment11 = Segment(segment10.a.x, segment10.a.y, 5, 0)
segment12 = Segment(segment11.a.x, segment11.a.y, 5, 0)
segment13 = Segment(segment12.a.x, segment12.a.y, 5, 0)
segment14 = Segment(segment13.a.x, segment13.a.y, 5, 0)
segment15 = Segment(segment14.a.x, segment14.a.y, 5, 0)
segment16 = Segment(segment15.a.x, segment15.a.y, 5, 0)
segment17 = Segment(segment16.a.x, segment16.a.y, 5, 0)
segment18 = Segment(segment17.a.x, segment17.a.y, 5, 0)
segment19 = Segment(segment18.a.x, segment18.a.y, 5, 0)
segment20 = Segment(segment19.a.x, segment19.a.y, 5, 0)
segment21 = Segment(segment20.a.x, segment20.a.y, 5, 0)
segment22 = Segment(segment21.a.x, segment21.a.y, 5, 0)
segment23 = Segment(segment22.a.x, segment22.a.y, 5, 0)
segment24 = Segment(segment23.a.x, segment23.a.y, 5, 0)
segment25 = Segment(segment24.a.x, segment24.a.y, 5, 0)
segment26 = Segment(segment25.a.x, segment25.a.y, 5, 0)
segment27 = Segment(segment26.a.x, segment26.a.y, 5, 0)
segment28 = Segment(segment27.a.x, segment27.a.y, 5, 0)
segment29 = Segment(segment28.a.x, segment28.a.y, 5, 0)
segment30 = Segment(segment29.a.x, segment29.a.y, 5, 0)
segment31 = Segment(segment30.a.x, segment30.a.y, 5, 0)
segment32 = Segment(segment31.a.x, segment31.a.y, 5, 0)
segment33 = Segment(segment32.a.x, segment32.a.y, 5, 0)
segment34 = Segment(segment33.a.x, segment33.a.y, 5, 0)
segment35 = Segment(segment34.a.x, segment34.a.y, 5, 0)
segment36 = Segment(segment35.a.x, segment35.a.y, 5, 0)
segment37 = Segment(segment36.a.x, segment36.a.y, 5, 0)
segment38 = Segment(segment37.a.x, segment37.a.y, 5, 0)
segment39 = Segment(segment38.a.x, segment38.a.y, 5, 0)
segment40 = Segment(segment39.a.x, segment39.a.y, 5, 0)
segment41 = Segment(segment40.a.x, segment40.a.y, 5, 0)
segment42 = Segment(segment41.a.x, segment41.a.y, 5, 0)
segment43 = Segment(segment42.a.x, segment42.a.y, 5, 0)
segment44 = Segment(segment43.a.x, segment43.a.y, 5, 0)
segment45 = Segment(segment44.a.x, segment44.a.y, 5, 0)
segment46 = Segment(segment45.a.x, segment45.a.y, 5, 0)
segment47 = Segment(segment46.a.x, segment46.a.y, 5, 0)
segment48 = Segment(segment47.a.x, segment47.a.y, 5, 0)
segment49 = Segment(segment48.a.x, segment48.a.y, 5, 0)
segment50 = Segment(segment49.a.x, segment49.a.y, 5, 0)
segment51 = Segment(segment50.a.x, segment50.a.y, 5, 0)
segment52 = Segment(segment51.a.x, segment51.a.y, 5, 0)
segment53 = Segment(segment52.a.x, segment52.a.y, 5, 0)
segment54 = Segment(segment53.a.x, segment53.a.y, 5, 0)
segment55 = Segment(segment54.a.x, segment54.a.y, 5, 0)
segment56 = Segment(segment55.a.x, segment55.a.y, 5, 0)
segment57 = Segment(segment56.a.x, segment56.a.y, 5, 0)
segment58 = Segment(segment57.a.x, segment57.a.y, 5, 0)
segment59 = Segment(segment58.a.x, segment58.a.y, 5, 0)
segment60 = Segment(segment59.a.x, segment59.a.y, 5, 0)
segment61 = Segment(segment60.a.x, segment60.a.y, 5, 0)
segment62 = Segment(segment61.a.x, segment61.a.y, 5, 0)
segment63 = Segment(segment62.a.x, segment62.a.y, 5, 0)
segment64 = Segment(segment63.a.x, segment63.a.y, 5, 0)
segment65 = Segment(segment64.a.x, segment64.a.y, 5, 0)
segment66 = Segment(segment65.a.x, segment65.a.y, 5, 0)


   
running = True

while running:
    
    for event in pygame.event.get():
        if event.type == pygame.QUIT:
            running = False

        if event.type == pygame.MOUSEMOTION:
            mouse_pos = pygame.mouse.get_pos()
            
            




    segment1.update()
    segment2.update()
    segment3.update()
    segment4.update()
    segment5.update()
    segment6.update()
    segment7.update()
    segment8.update()
    segment9.update()
    segment10.update()
    segment11.update()
    segment12.update()
    segment13.update()
    segment14.update()
    segment15.update()
    segment16.update()
    segment17.update()
    segment18.update()
    segment19.update()
    segment20.update()
    segment21.update()
    segment22.update()
    segment23.update()
    segment24.update()
    segment25.update()
    segment26.update()
    segment27.update()
    segment28.update()
    segment29.update()
    segment30.update()
    segment31.update()
    segment32.update()
    segment33.update()
    segment34.update()
    segment35.update()
    segment36.update()
    segment37.update()
    segment38.update()
    segment39.update()
    segment40.update()
    segment41.update()
    segment42.update()
    segment43.update()
    segment44.update()
    segment45.update()
    segment46.update()
    segment47.update()
    segment48.update()
    segment49.update()
    segment50.update()
    segment51.update()
    segment52.update()
    segment53.update()
    segment54.update()
    segment55.update()
    segment56.update()
    segment57.update()
    segment58.update()
    segment59.update()
    segment60.update()
    segment61.update()
    segment62.update()
    segment63.update()
    segment64.update()
    segment65.update()
    segment66.update()
    segment66.follow(mouse_pos[0], mouse_pos[1])
    segment65.follow(segment66.a.x, segment66.a.y)
    segment64.follow(segment65.a.x, segment65.a.y)
    segment63.follow(segment64.a.x, segment64.a.y)
    segment62.follow(segment63.a.x, segment63.a.y)
    segment61.follow(segment62.a.x, segment62.a.y)
    segment60.follow(segment61.a.x, segment61.a.y)
    segment59.follow(segment60.a.x, segment60.a.y)
    segment58.follow(segment59.a.x, segment59.a.y)
    segment57.follow(segment58.a.x, segment58.a.y)
    segment56.follow(segment57.a.x, segment57.a.y)
    segment55.follow(segment56.a.x, segment56.a.y)
    segment54.follow(segment55.a.x, segment55.a.y)
    segment53.follow(segment54.a.x, segment54.a.y)
    segment52.follow(segment53.a.x, segment53.a.y)
    segment51.follow(segment52.a.x, segment52.a.y)
    segment50.follow(segment51.a.x, segment51.a.y)
    segment49.follow(segment50.a.x, segment50.a.y)
    segment48.follow(segment49.a.x, segment49.a.y)
    segment47.follow(segment48.a.x, segment48.a.y)
    segment46.follow(segment47.a.x, segment47.a.y)
    segment45.follow(segment46.a.x, segment46.a.y)
    segment44.follow(segment45.a.x, segment45.a.y)
    segment43.follow(segment44.a.x, segment44.a.y)
    segment42.follow(segment43.a.x, segment43.a.y)
    segment41.follow(segment42.a.x, segment42.a.y)
    segment40.follow(segment41.a.x, segment41.a.y)
    segment39.follow(segment40.a.x, segment40.a.y)
    segment38.follow(segment39.a.x, segment39.a.y)
    segment37.follow(segment38.a.x, segment38.a.y)
    segment36.follow(segment37.a.x, segment37.a.y)
    segment35.follow(segment36.a.x, segment36.a.y)
    segment34.follow(segment35.a.x, segment35.a.y)
    segment33.follow(segment34.a.x, segment34.a.y)
    segment32.follow(segment33.a.x, segment33.a.y)
    segment31.follow(segment32.a.x, segment32.a.y)
    segment30.follow(segment31.a.x, segment31.a.y)
    segment29.follow(segment30.a.x, segment30.a.y)
    segment28.follow(segment29.a.x, segment29.a.y)
    segment27.follow(segment28.a.x, segment28.a.y)
    segment26.follow(segment27.a.x, segment27.a.y)
    segment25.follow(segment26.a.x, segment26.a.y)
    segment24.follow(segment25.a.x, segment25.a.y)
    segment23.follow(segment24.a.x, segment24.a.y)
    segment22.follow(segment23.a.x, segment23.a.y)
    segment21.follow(segment22.a.x, segment22.a.y)
    segment20.follow(segment21.a.x, segment21.a.y)
    segment19.follow(segment20.a.x, segment20.a.y)
    segment18.follow(segment19.a.x, segment19.a.y)
    segment17.follow(segment18.a.x, segment18.a.y)
    segment16.follow(segment17.a.x, segment17.a.y)
    segment15.follow(segment16.a.x, segment16.a.y)
    segment14.follow(segment15.a.x, segment15.a.y)
    segment13.follow(segment14.a.x, segment14.a.y)
    segment12.follow(segment13.a.x, segment13.a.y)
    segment11.follow(segment12.a.x, segment12.a.y)
    segment10.follow(segment11.a.x, segment11.a.y)
    segment9.follow(segment10.a.x, segment10.a.y)
    segment8.follow(segment9.a.x, segment9.a.y)
    segment7.follow(segment8.a.x, segment8.a.y)
    segment6.follow(segment7.a.x, segment7.a.y)
    segment5.follow(segment6.a.x, segment6.a.y)
    segment4.follow(segment5.a.x, segment5.a.y)
    segment3.follow(segment4.a.x, segment4.a.y)
    segment2.follow(segment3.a.x, segment3.a.y)
    segment1.follow(segment2.a.x, segment2.a.y)
    screen.fill((0, 0, 0))
    segment1.show(screen)
    segment2.show(screen)
    segment3.show(screen)
    segment4.show(screen)
    segment5.show(screen)
    segment6.show(screen)
    segment7.show(screen)
    segment8.show(screen)
    segment9.show(screen)
    segment10.show(screen)
    segment11.show(screen)
    segment12.show(screen)
    segment13.show(screen)
    segment14.show(screen)
    segment13.show(screen)
    segment14.show(screen)
    segment15.show(screen)
    segment16.show(screen)
    segment17.show(screen)
    segment18.show(screen)
    segment19.show(screen)
    segment20.show(screen)
    segment21.show(screen)
    segment22.show(screen)
    segment23.show(screen)
    segment24.show(screen)
    segment25.show(screen)
    segment26.show(screen)
    segment27.show(screen)
    segment28.show(screen)
    segment29.show(screen)
    segment30.show(screen)
    segment31.show(screen)
    segment32.show(screen)
    segment33.show(screen)
    segment34.show(screen)
    segment35.show(screen)
    segment36.show(screen)
    segment37.show(screen)
    segment38.show(screen)
    segment39.show(screen)
    segment40.show(screen)
    segment41.show(screen)
    segment42.show(screen)
    segment43.show(screen)
    segment44.show(screen)
    segment45.show(screen)
    segment46.show(screen)
    segment47.show(screen)
    segment48.show(screen)
    segment49.show(screen)
    segment50.show(screen)
    segment51.show(screen)
    segment52.show(screen)
    segment53.show(screen)
    segment54.show(screen)
    segment55.show(screen)
    segment56.show(screen)
    segment57.show(screen)
    segment58.show(screen)
    segment59.show(screen)
    segment60.show(screen)
    segment61.show(screen)
    segment62.show(screen)
    segment63.show(screen)
    segment64.show(screen)
    segment65.show(screen)
    segment66.show(screen)
    
    
    pygame.display.update()
    clock.tick(60)

pygame.quit()

    
